# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_read_out_of_bound <- function(val) {
    .Call(`_testSAN_rcpp_read_out_of_bound`, val)
}

rcpp_use_after_deallocate <- function(val) {
    .Call(`_testSAN_rcpp_use_after_deallocate`, val)
}

rcpp_use_after_free <- function(val) {
    .Call(`_testSAN_rcpp_use_after_free`, val)
}

rcpp_write_index_outofbound <- function(val) {
    .Call(`_testSAN_rcpp_write_index_outofbound`, val)
}

rcpp_zero_sized_array <- function(val) {
    .Call(`_testSAN_rcpp_zero_sized_array`, val)
}

