// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_binseg_normal
Rcpp::List rcpp_binseg_normal(const Rcpp::NumericVector data_vec, const Rcpp::IntegerVector max_segments);
RcppExport SEXP _binsegRcpp_rcpp_binseg_normal(SEXP data_vecSEXP, SEXP max_segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type data_vec(data_vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type max_segments(max_segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_binseg_normal(data_vec, max_segments));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_binseg_normal_cost
Rcpp::List rcpp_binseg_normal_cost(const Rcpp::NumericVector data_vec, const Rcpp::IntegerVector max_segments);
RcppExport SEXP _binsegRcpp_rcpp_binseg_normal_cost(SEXP data_vecSEXP, SEXP max_segmentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type data_vec(data_vecSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector >::type max_segments(max_segmentsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_binseg_normal_cost(data_vec, max_segments));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_binsegRcpp_rcpp_binseg_normal", (DL_FUNC) &_binsegRcpp_rcpp_binseg_normal, 2},
    {"_binsegRcpp_rcpp_binseg_normal_cost", (DL_FUNC) &_binsegRcpp_rcpp_binseg_normal_cost, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_binsegRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
