R_HOME= /home/akhila/lib/R
COMMON_FLAGS = /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF.o -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/include -I${HOME}/.RcppDeepState/deepstate-master/build_LF -I${HOME}/.RcppDeepState/deepstate-master/src/include -L/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RInside/lib -Wl,-rpath=/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RInside/lib -L${R_HOME}/lib -Wl,-rpath=${R_HOME}/lib -L${HOME}/.RcppDeepState/deepstate-master/build_LF -Wl,-rpath=${HOME}/.RcppDeepState/deepstate-master/build_LF -lR -lRInside -ldeepstate -ldeepstate_LF

/home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/libfuzzer_rcpp_write_index_outofbound_log : /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF
	cd /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound && valgrind --xml=yes --xml-file=/home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/libfuzzer_rcpp_write_index_outofbound_log --tool=memcheck --leak-check=yes --track-origins=yes ./rcpp_write_index_outofbound_DeepState_TestHarness --fuzz 

/home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF : /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF.o
	clang++ -g -o /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF ${COMMON_FLAGS} -I${R_HOME}/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include -I${HOME}/.RcppDeepState/deepstate-master/src/include /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/src/*.cpp

/home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF.o : /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness.cpp
	clang++ -g -I${R_HOME}/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RcppArmadillo/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/qs/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RInside/include -I/home/akhila/R/x86_64-pc-linux-gnu-library/3.6/RcppDeepState/include /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness.cpp -o /home/akhila/R/RcppDeepState/inst/testpkgs/testSAN/inst/testfiles/rcpp_write_index_outofbound/rcpp_write_index_outofbound_DeepState_TestHarness_LF.o -c
