##' @title TestHarness for the function
##' @param package_path to the test package
##' @param function_name from the test package
##' @param sep infun default
##' @description The function creates Testharness for the provided function name.
##' @examples 
##' path <- system.file("testpkgs/testSAN", package = "RcppDeepState")
##' function_name <- "rcpp_read_out_of_bound"
##' function.harness <- deepstate_fun_create(path,function_name)
##' print(function.harness)
##' @return The TestHarness file that is generated
##' @export
deepstate_fun_create<-function(package_path,function_name,sep="infun"){
  inst_path <- file.path(package_path, "inst")
  test_path <- file.path(inst_path,"testfiles")
  
  if(!dir.exists(inst_path)){
    dir.create(inst_path,showWarnings = FALSE)
    dir.create(test_path,showWarnings = FALSE)
  }
  primitives <- list()
  packagename <- basename(package_path)
  functions.list <- RcppDeepState::deepstate_get_function_body(package_path)
  functions.list$argument.type<-gsub("Rcpp::","",functions.list$argument.type)
  prototypes_calls <-RcppDeepState::deepstate_get_prototype_calls(package_path)
  if(sep=="generation" ||  sep == "checks"){ 
    if(is.null(functions.list) || length(functions.list) < 1){
      stop("No Rcpp Function to test in the package")
    }
  }
  headers <-"#include <fstream>\n#include <RInside.h>\n#include <iostream>\n#include <RcppDeepState.h>\n#include <qs.h>\n#include <DeepState.hpp>\n"
  write_to_file <- ""
  functions.rows  <- functions.list[functions.list$funName == function_name,]
  params <- c(functions.rows$argument.type)
  if(RcppDeepState::deepstate_datatype_check(params) == 1){
    pt <- prototypes_calls[prototypes_calls$funName == function_name,]
    fun_name <-function_name
    filename <- if(sep == "generation" || sep == "checks"){
      paste0(fun_name,"_DeepState_TestHarness_",sep,".cpp")
    }else{
      paste0(fun_name,"_DeepState_TestHarness.cpp")
    }
    fun_path <- file.path(test_path,fun_name)
    if(!dir.exists(fun_path)){
      dir.create(fun_path)
      #unlink(fun_path, recursive = TRUE)
    }
    
    if(sep == "generation" || sep == "checks"){
      gen.path <- file.path(fun_path,paste0(fun_name,"_DeepState_TestHarness_",sep,".cpp"))
      makesep.path <- file.path(fun_path,paste0(sep,".Makefile"))
      filename <- basename(gen.path)
      file_path <- file.path(fun_path,filename)
      file.create(file_path,recursive=TRUE)
      if(file.exists(file.path(fun_path,"Makefile"))){
        file.copy(file.path(fun_path,"Makefile"),makesep.path)
      }else{
        deepstate_create_makefile(package_path,fun_name)
        #file.copy(file.path(fun_path,"Makefile"),makegen.path)
      }
      makefile_lines <- readLines(file.path(fun_path,"Makefile"),warn=FALSE)
      makefile_lines <- gsub(file.path(fun_path,paste0(fun_name,"_DeepState_TestHarness")),
                             file.path(fun_path,paste0(fun_name,"_DeepState_TestHarness_",sep)),makefile_lines,fixed=TRUE)
      file.create(makesep.path,recursive=TRUE)
      cat(makefile_lines, file=makesep.path, sep="\n")
      unlink(file.path(fun_path,"Makefile"))
      #dir.create(file.path(testable_path,"inputs"),showWarnings = FALSE)
      dir.create(file.path(fun_path,paste0(fun_name,"_output","_",sep)),showWarnings = FALSE)
    }else{
      file_path <- file.path(fun_path,filename)
      file.create(file_path,recursive=TRUE)
      deepstate_create_makefile(package_path,fun_name)
    }
    comment <- paste0("// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT\n// ",
                      fun_name,"_DeepState_TestHarness_generation.cpp and ",fun_name,"_DeepState_TestHarness_checks.cpp\n\n")
    
    #write_to_file <-
    if(sep == "generation" || sep == "checks"){
      write(headers,file_path,append = TRUE)
    }else{
      write(paste0(write_to_file,comment,headers),file_path,append = TRUE)
    }
    write_to_file <-paste0(write_to_file,pt[1,pt$prototype],"\n")
    testname<-paste0(function_name,"_test",sep="")
    unittest<-paste0(packagename,"_deepstate_test")
    write_to_file <- paste0(write_to_file,"\n","TEST(",unittest,",",testname,")","{","\n")
    #obj <-gsub( "\\s+", " " ,paste(in_package,tolower(in_package),";","\n"))
    #write(obj,filename,append = TRUE)
    indent <- "  "
    write_to_file<-paste0(write_to_file,indent,"RInside R;\n",indent,"std::cout << #input starts# << std::endl;\n")
    proto_args <-""
    for(argument.i in 1:nrow(functions.rows)){
      arg.type <- gsub(" ","",functions.rows [argument.i,argument.type])
      arg.name <- gsub(" ","",functions.rows [argument.i,argument.name])
      type.arg <- gsub("const","", arg.type)
      type.arg <-gsub("Rcpp::","",type.arg)
      type.arg <-gsub("arma::","",type.arg)
      st_val <- if(sep == "generation"){
        paste0("= ","RcppDeepState_",(type.arg),"()","; //RANGE OF THE VECTOR CAN BE ADDED HERE\n")
      }else{
        paste0("= ","RcppDeepState_",(type.arg),"()",";\n")
      }
      inputs_path <- file.path(fun_path,"inputs")
      if(!dir.exists(inputs_path)){
        dir.create(inputs_path)
      }
      if(type.arg == "mat"){
        write_to_file<-paste0(write_to_file,indent,"std::ofstream ",
                              gsub(" ","",arg.name),"_stream",";\n")
        input.vals <- file.path(inputs_path,arg.name)
        file_open <- gsub("# ","\"",paste0(arg.name,"_stream.open(#",input.vals,"# );","\n",indent,
                                           arg.name,"_stream << ", 
                                           arg.name,";","\n",indent,
                                           "std::cout << ","#",arg.name,
                                           " values: ","#"," << ",arg.name,
                                           " << std::endl;","\n",indent,
                                           arg.name,"_stream.close();","\n"))
      }
      else{
        if(sep == "generation"){
          if(type.arg == "int"){
            variable <- paste0("IntegerVector ",arg.name,"(1);","\n",indent,"//RcppDeepState_",type.arg,"(low,high)","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }
          else if(type.arg == "double") {
            variable <- paste0("NumericVector ",arg.name,"(1);","\n",indent,"//RcppDeepState_",type.arg,"(low,high)","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }
          else if(type.arg == "std::string")
          {
            variable <- paste0("CharacterVector ",arg.name,"(1);","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }
          else if(type.arg == "NumericVector" || type.arg == "IntegerVector"){
            variable <- paste0("//RcppDeepState_",type.arg,"(size,low,high)","\n",indent,arg.type," ",arg.name)
          }
          else if(type.arg == "NumericMatrix"){
            variable <- paste0("//RcppDeepState_",type.arg,"(row,column,low,high)","\n",indent,arg.type," ",arg.name)
          }
        }else{
          if(type.arg == "int"){
            variable <- paste0("IntegerVector ",arg.name,"(1);","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }
          else if(type.arg == "double") {
            variable <- paste0("NumericVector ",arg.name,"(1);","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }
          else if(type.arg == "std::string")
          {
            variable <- paste0("CharacterVector ",arg.name,"(1);","\n",indent,arg.name,"[0]")
            primitives <- c(primitives,arg.name)
          }else{
            variable <- paste0(arg.type," ",arg.name)
          }
        }
        variable <- gsub("const","",variable)
        arg.file <- paste0(arg.name,".qs")
        input.vals <- file.path(inputs_path,arg.file)
        file_open <- gsub("# ","\"",paste0("qs::c_qsave(",arg.name,",#",input.vals,"#,\n","\t\t#high#, #zstd#, 1, 15, true, 1);\n",indent,
                                           "std::cout << ","#",arg.name," values: ","#"," << ",arg.name,
                                           " << std::endl;","\n"))
      }
      proto_args <- gsub(" ","",paste0(proto_args,arg.name))
      if(argument.i <= nrow(functions.rows)) {
        if(type.arg == "int" || type.arg == "double" || type.arg == "std::string"){
          proto_args <- paste0(proto_args,"[0],")
        }else{
          proto_args <- paste0(proto_args,",")  
        }
      }
      write_to_file <- paste0(write_to_file,indent,paste0(variable,indent,st_val,indent,file_open))
    }
    write_to_file<-paste0(write_to_file,indent,"std::cout << #input ends# << std::endl;\n",indent,"try{\n")
    write_to_file<-paste0(write_to_file,indent,indent,fun_name,"(",gsub(",$","",proto_args),");\n")
    if(sep == "checks"){
      write_to_file<-paste0(write_to_file,indent,"//ASSERT CONDITIONS CAN BE ADDED HERE\n") 
    }
    write_to_file<-gsub("#","\"",paste0(write_to_file,indent,"}\n",indent,"catch(Rcpp::exception& e){\n",indent,indent,"std::cout<<#Exception Handled#<<std::endl;\n",indent,"}"))
    write_to_file<-paste0(write_to_file,"\n","}")
    write(write_to_file,file_path,append=TRUE)
    return(filename)
  } else if(deepstate_datatype_check(params) == 0){
    return(NA_character_)
  }
  
}
